name: registry

services:
  nginx:
    image: darktoolz/registry
    build: .
    env_file: ${host}.env
    hostname: ${host}
    restart: always
    read_only: true
    ports:
      - ${http_port}:80
      - ${https_port}:443
    volumes:
      - /etc/keys
      - /var/tmp
      - /var/www
    tmpfs:
      - /tmp:size=128M,uid=65534,gid=65533,mode=1777
      - /run:size=128M,uid=65534,gid=65533,mode=1777
  registry:
    image: registry:2
    env_file: ${host}.env
    restart: always
    volumes:
      - /var/lib/registry
